name: NodeJS Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: |
          This is the name of the person or entity. 
          You can provide a full name or a username, depending on the context of your workflow.\n
          For more information on how to format this field, please refer to the 
          [documentation](https://example.com/format-guide).
        type: string
        default: 'dev'

      comment: 
        description: |
          Cucumber tags to run | \\n
          🏷️ @smoke 🏷️ @regression | \\n
          🏷️ @api 🏷️ @ui 🔄 Combine: | \\n
          "@smoke and not @wip" or "@api or @ui"
        required: false
        default: '@smoke'
        type: string
       
      environment2:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.environment}}

   
    steps:
    - uses: actions/checkout@v4

    - name: Debug 
      run: |
        echo "comment: ${{ github.event.inputs.comment }}"

    - name: Debug Specific Variables with env
      run: |
        echo "Printing specific environment variables..."
        echo "BASE_URL: $BASE_URL"  # Accessing the BASE_URL from environment
        echo "API_KEY: $API_KEY"    # Accessing the API_KEY from environment
        echo "environment: $environment"  # Accessing the environment input variable
      env:
        BASE_URL: ${{ vars.BASE_URL }}  # Explicitly pass BASE_URL to env
        API_KEY: ${{ vars.API_KEY }}  # Pass API_KEY from secrets
        environment: ${{ github.event.inputs.environment }}  # Pass environment from inputs

    - name: Debug vars
      run: |
        
        echo "BASE_URL: ${{ vars.BASE_URL }}"  # Accessing the BASE_URL from environment
        echo "API_KEY: ${{ vars.API_KEY }}    # Accessing the API_KEY from environment
        echo "environment: ${{ github.event.inputs.environment }}"  # Accessing the environment input variable
             
